export const WEATHER_MAP = {
  晴: "tianqitubiao_qing",
  阵雨: "zhenyu",
  少云: "shaoyun",
  雷阵雨: "tianqitubiao_leizhenyujiaxue",
  晴间多云: "tianqitubiao_duoyun",
  多云: "tianqitubiao_duoyun",
  阴: "tianqitubiao_yin",
  有风: "youfeng",
  和风: "youfeng",
  清风: "youfeng",
  平静: "pingjing",
  强风: "tianqitubiao_dafeng",
  劲风: "tianqitubiao_dafeng",
  "强风/劲风": "tianqitubiao_dafeng",
  疾风: "tianqitubiao_dafeng",
  大风: "tianqitubiao_dafeng",
  烈风: "tianqitubiao_dafeng",
  风暴: "tianqitubiao_taifeng",
  狂爆风: "tianqitubiao_taifeng",
  飓风: "tianqitubiao_taifeng",
  热带风暴: "tianqitubiao_taifeng",
  霾: "tianqitubiao_wumai",
  中度霾: "tianqitubiao_wumai",
  重度霾: "tianqitubiao_wumai",
  严重霾: "tianqitubiao_wumai",
  雷阵雨并伴有冰雹: "leizhenyubingbanyoubingbao",
  小雨: "tianqitubiao_xiaoyu",
  中雨: "tianqitubiao_zhongyu",
  大雨: "tianqitubiao_dayu",
  暴雨: "baoyudaodabaoyu",
  大暴雨: "baoyudaodabaoyu",
  强阵雨: "qiangzhenyu",
  强雷阵雨: "qiangleizhenyu",
  极端降雨: "qiangleizhenyu",
  "毛毛雨/细雨": "tianqitubiao_xiaoyu",
  "小雨-中雨": "tianqitubiao_xiaoyu",
  "中雨-大雨": "tianqitubiao_dayu",
  "大雨-暴雨": "tianqitubiao_dayu",
  "暴雨-大暴雨": "baoyudaodabaoyu",
  "大暴雨-特大暴雨": "baoyudaodabaoyu",
  雨雪天气: "yuxuetianqi-yujiaxue-zhenyujiaxue",
  雨夹雪: "yuxuetianqi-yujiaxue-zhenyujiaxue",
  阵雨夹雪: "mianxingdongyu",
  阵雪: "zhenxue",
  雪: "tianqitubiao_daxue",
  小雪: "tianqitubiao_xiaoxue",
  中雪: "tianqitubiao_zhongxue",
  大雪: "tianqitubiao_daxue",
  暴雪: "baoxue",
  "小雪-中雪": "tianqitubiao_xiaoxue",
  "中雪-大雪": "tianqitubiao_daxue",
  "大雪-暴雪": "baoxue",
  浮尘: "fuchenyangsha",
  扬沙: "yangsha",
  沙尘暴: "shachenbao",
  强沙尘暴: "shachenbao",
  龙卷风: "tianqitubiao_longjuanfeng",
  雾: "wu",
  浓雾: "a-nongwuqiangnongwuteqiangnongwu",
  强浓雾: "a-nongwuqiangnongwuteqiangnongwu",
  轻雾: "wu",
  大雾: "a-nongwuqiangnongwuteqiangnongwu",
  特强浓雾: "a-nongwuqiangnongwuteqiangnongwu",
  热: "tianqitubiao_qing",
  冷: "tianqitubiao_daxue",
  未知: "huaban",
};

export const enum WEEK_DAY {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
}

export const WEEK_DAY_MAP = {
  "1": "星期一",
  "2": "星期二",
  "3": "星期三",
  "4": "星期四",
  "5": "星期五",
  "6": "星期六",
  "7": "星期日",
};
